version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  api:
    build: .
    command: "./docker-entrypoint.sh"
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app
