# Generated by Django 3.1.1 on 2020-09-28 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenda',
            options={'ordering': ['day'], 'verbose_name': 'Agenda', 'verbose_name_plural': 'Agendas'},
        ),
        migrations.AlterModelOptions(
            name='medicalappointment',
            options={'ordering': ['id'], 'verbose_name': 'Consulta', 'verbose_name_plural': 'Consultas'},
        ),
    ]
