name: Medicar CI

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build the Docker image
      run: docker-compose -f ./backend/docker-compose.yml build --no-cache

    - name: Run tests
      run: docker-compose -f ./backend/docker-compose.yml run --rm api pytest